services:
  polaris_ultrasound:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polaris_ultrasound
    volumes:
      # 挂载 ROM 文件目录
      - ./rom_files:/opt/ndi/rom_files
      # 挂载源代码目录
      - ./src:/ros2_ws/src/polaris_ultrasound
      # 挂载数据输出目录
      - ./calibration_data:/ros2_ws/calibration_data
      # 挂载设备目录
      - /dev:/dev
    devices:
      # 允许访问 Polaris 设备 (通常是 USB 串口)
      - /dev/ttyUSB0:/dev/ttyUSB0
      # 允许访问超声设备 (视频捕获设备)
      - /dev/video0:/dev/video0
      # 如果有其他视频设备，也可以添加
      - /dev/video1:/dev/video1
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=1
      # 如果需要使用 GUI，还需要添加以下行
      - XAUTHORITY=/home/$USER/.Xauthority
    network_mode: host
    privileged: true
    # 启动命令，保持容器运行
    command: tail -f /dev/null